export default function Head() {
  return (
    <>
      <title>M Burmeister</title>
      <meta
        name="theme-color"
        media="prefers-color-scheme: dark"
        content="#bbf7d0"
      />
      <meta
        name="theme-color"
        media="prefers-color-scheme: light"
        content="#bbf7d0"
      />
      <meta name="theme-color" content="#bbf7d0" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      <link rel="manifest" href="/site.webmanifest" />

      <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
    </>
  );
}
